## 0. Configs

In [4]:
import locale
locale.setlocale(locale.LC_ALL, '')

def as_currency(amount):
    return locale.currency(amount, grouping=True)

In [5]:
import warnings

warnings.filterwarnings('ignore')

## 1. Import libraries and data

In [6]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error


df = pd.read_csv("../data/cleaned/train_V2_cleaned.csv")
df.head()

,income_am,profit_last_am,profit_am,damage_am,damage_inc,crd_lim_rec,credit_use_ic,gluten_ic,lactose_ic,insurance_ic,...,nights_booked,shop_am,shop_use,retired,gold_status,outcome_profit,outcome_damage_inc,outcome_damage_amount,gender_M,gender_V
0,268.0,16.0,1682.0,0.0,0.0,750.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.000000,0.0,0.0,1672.78,1,829.66,1,0
1,283.0,23.0,1673.0,0.0,0.0,750.0,0.0,0.0,0.0,1.0,...,6.0,0.0,0.000000,0.0,0.0,1001.40,0,0.00,1,0
2,227.0,0.0,1685.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.000000,0.0,0.0,1785.59,0,0.00,0,1
3,227.0,0.0,1620.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.151873,0.0,0.0,1127.05,0,0.00,0,1
4,229.0,810.0,1620.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.000000,0.0,0.0,1640.31,0,0.00,1,0